CREATE TABLE "suppliers" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "suppliers_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"contact_info" varchar(255),
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "uom" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "uom_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"description" varchar(255),
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "products" ADD COLUMN "supplier_id" integer;--> statement-breakpoint
ALTER TABLE "products" ADD COLUMN "uom_id" ;--> statement-breakpoint
ALTER TABLE "products" ADD COLUMN "pkg" ;--> statement-breakpoint
ALTER TABLE "products" ADD COLUMN "barcode" varchar(255);--> statement-breakpoint
ALTER TABLE "products" ADD CONSTRAINT "products_supplier_id_categories_id_fk" FOREIGN KEY ("supplier_id") REFERENCES "public"."categories"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "products" ADD CONSTRAINT "products_uom_id_categories_id_fk" FOREIGN KEY ("uom_id") REFERENCES "public"."categories"("id") ON DELETE restrict ON UPDATE no action;