CREATE TABLE IF NOT EXISTS "branches" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "name" varchar(255) NOT NULL,
  "created_at" timestamp DEFAULT now() NOT NULL,
  "updated_at" timestamp DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS "monthly_inventory" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "product_id" integer NOT NULL REFERENCES "products"("id") ON DELETE restrict ON UPDATE no action,
  "branch_id" integer NOT NULL REFERENCES "branches"("id") ON DELETE restrict ON UPDATE no action,
  "month" date NOT NULL,
  "quantity" integer NOT NULL,
  "stock_value" numeric(12, 2)
);

CREATE UNIQUE INDEX IF NOT EXISTS "monthly_inventory_branch_product_month_idx"
ON "monthly_inventory" ("branch_id", "product_id", "month");
