CREATE TYPE "public"."branch_assignment_status" AS ENUM('not started', 'in progress', 'done');--> statement-breakpoint
CREATE TABLE "stocktake_summaries" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "stocktake_summaries_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"branch_assignment_id" integer NOT NULL,
	"grand_total" numeric(12, 2) NOT NULL,
	"totals_by_category" jsonb NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "stocktake_summaries_branch_assignment_id_unique" UNIQUE("branch_assignment_id")
);
--> statement-breakpoint
ALTER TABLE "monthly_inventory" DROP CONSTRAINT "monthly_inventory_branch_id_branches_id_fk";
--> statement-breakpoint
ALTER TABLE "branch_assignments" ADD COLUMN "status" "branch_assignment_status" DEFAULT 'in progress' NOT NULL;--> statement-breakpoint
ALTER TABLE "branch_assignments" ADD COLUMN "assigned_at" timestamp DEFAULT now() NOT NULL;--> statement-breakpoint
ALTER TABLE "monthly_inventory" ADD COLUMN "branch_assignments_id" integer NOT NULL;--> statement-breakpoint
ALTER TABLE "monthly_inventory" ADD COLUMN "updated_at" timestamp DEFAULT now() NOT NULL;--> statement-breakpoint
ALTER TABLE "suppliers" ADD COLUMN "website" varchar(255);--> statement-breakpoint
ALTER TABLE "stocktake_summaries" ADD CONSTRAINT "stocktake_summaries_branch_assignment_id_branch_assignments_id_fk" FOREIGN KEY ("branch_assignment_id") REFERENCES "public"."branch_assignments"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "monthly_inventory" ADD CONSTRAINT "monthly_inventory_branch_assignments_id_branch_assignments_id_fk" FOREIGN KEY ("branch_assignments_id") REFERENCES "public"."branch_assignments"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "branch_assignments" DROP COLUMN "created_at";--> statement-breakpoint
ALTER TABLE "monthly_inventory" DROP COLUMN "branch_id";--> statement-breakpoint
ALTER TABLE "monthly_inventory" DROP COLUMN "month";--> statement-breakpoint
ALTER TABLE "branch_assignments" ADD CONSTRAINT "branch_assignments_branch_id_unique" UNIQUE("branch_id");