DO $$
BEGIN
  CREATE TABLE "branch_assignments" (
    "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "name" varchar(255) NOT NULL,
    "branch_id" integer NOT NULL REFERENCES "branches"("id") ON DELETE restrict ON UPDATE no action,
    "assigned_month" date NOT NULL
  );
EXCEPTION
  WHEN duplicate_table THEN NULL;
END $$;
